[package]
name = "binius_utils"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
cfg-if.workspace = true
bytes.workspace = true
bytemuck = { workspace = true, features = ["extern_crate_alloc"] }
itertools.workspace = true
rayon.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-profile = { workspace = true, optional = true }
tracing-subscriber.workspace = true
tracing-tracy = { workspace = true, optional = true }
thread_local.workspace = true

[features]
default = []
bail_panic = []
ittapi = ["tracing-profile/ittapi"]
perf_counters = ["tracing-profile/perf_counters"]
perfetto = ["tracing-profile/perfetto"]
tracing = ["dep:tracing-profile"]
tracy = ["tracing-tracy"]